[package]
name = "flashyi/boiler"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"
Janitor = "howmanysmall/janitor@1.18.3"
Observer = "tazmondo/observer@0.3.4"
CameraShaker = "brittonfischer/camerashaker@0.1.0"

Conch = "alicesaidhi/conch@0.3.0-rc.6"
ConchUI = "alicesaidhi/conch-ui@0.3.0-rc.6"

DataService = "leifstout/dataservice@0.4.0"
Networker = "leifstout/networker@0.3.0"

Signal = "sleitnick/signal@2.0.3"
Replica = "ayrezrblx/replica@0.1.9"



Zoneplus = "mattschrubb/zoneplus@3.2.0"

Richtext = "lipetos/richtext@0.1.2"

Charm = "neohertz/charm@0.11.0"

React = "jsdotlua/react@17.2.1"
ReactRoblox = "jsdotlua/react-roblox@17.2.1"
Ripple = "littensy/ripple@0.9.3"
ReactCharm = "littensy/react-charm@0.3.0"
ReactErrorBoundary = "chriscerie/react-error-boundary@0.2.0"

Sift = "csqrl/sift@0.0.11"

Topbarplus = "1foreverhd/topbarplus@3.4.0"

ServicePlayerData = "leifstout/serviceplayerdata@0.1.2"

